#!/bin/sh

if [ $(id -u) -eq 0 ]; then
  USER=$(find $XAUTHORITY -printf '%u')
  exec runuser -u $USER -- env DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u $USER)/bus x-www-browser "$@"
else
  exec x-www-browser "$@"
fi

